language: python

python:
  - "2.7"

branches:
  only:
    - master

install:
  - pip install codecov
  - python setup.py install

script:
  - python setup.py flake8
  - python setup.py test
  - codecov
